# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 100

  # Optimizer learning rate
  lr: 5

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.75

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /public1/home/wangsw/FWI/FIELDDATA/OBN/data/p01_Geo_1ms_0.5s.npy

  arrival_mask: /public1/home/wangsw/FWI/FIELDDATA/OBN/data/p01_Geo_1ms_first0.5s_ArrivalMask.npy
  #/public1/home/wangsw/FWI/FIELDDATA/OBN/data/p01_Geo_1ms_first1s_ArrivalMask.npy
  #/public1/home/wangsw/FWI/FIELDDATA/OBN/data/p01_Geo.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /public1/home/wangsw/FWI/FIELDDATA/OBN/velocity/linear.npy
    vs:
    rho:
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: /public1/home/wangsw/FWI/FIELDDATA/OBN/geom/sources.pkl

  receivers: /public1/home/wangsw/FWI/FIELDDATA/OBN/geom/receivers.pkl

  seabed: /public1/home/wangsw/FWI/FIELDDATA/OBN/velocity/seabed.npy

  boundary_saving: true

  multiple: true

  wavelet: /public1/home/wangsw/FWI/FIELDDATA/OBN/geom/inverted_wavelet.npy
  # /public1/home/wangsw/FWI/FIELDDATA/OBN/geom/inverted_wavelet_e030.npy
  # /public1/home/wangsw/FWI/FIELDDATA/OBN/geom/inverted_wavelet.npy
  # ./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /public1/home/wangsw/FWI/FIELDDATA/OBN/velocity/linear.npy
    #/public1/home/wangsw/FWI/FIELDDATA/OBN/velocity/fatt.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs: false
    rho: false
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_10m/Test

  multiscale:
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 500

  # Main frequency of ricker wave
  fm: 10.0

  wavelet_delay: 30

  wavelet_inverse: true

  # Spatial grid step size
  h: 12.5

  # Total Shots
  Nshots: 999

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
