# Random seed for pytorch and all shuffle functions
seed: 20230503

name: forward_modeling

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: elastic

training:

  smooth:
    counts: 5 # the number of smooth times
    radius: # the radius of smooth in x and z direction
      x: 1
      z: 1
    sigma: # the sigma of smooth in x and z direction
      x: 1
      z: 1

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 10

  # Number of training epochs
  N_epochs: 50

  # Optimizer learning rate
  lr: 0.001

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.85

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: ./obs.hdf5

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: ./velocity/true_vp.npy
    vs: ./velocity/true_vs.npy
    rho: ./velocity/rho.npy
    Q: 
    

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  seabed: /home/shaowinw/seistorch/examples/models/marmousi_model/seabed.npy

  wavelet:

  multiple: false

  boundary_saving: true

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - vz

  receiver_type:
    - vx
    - vz

  # Inital Wave speed model from disk_file
  initPath: 
    vp:
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs:
    rho:
    q:

  # Save the results of FWI
  inv_savePath:

  multiscale:
  - 1.0
  - 3.0
  - 5.0
  - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 10.0

  # Spatial grid step size
  h: 20.0

  # Total Shots
  Nshots: 99

  boundary:
    type: pml
    width: 50
