# Random seed for pytorch and all shuffle functions
seed: 20230503

name: forward_modeling

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  smooth:
    counts: 10 # the number of smooth times
    radius: # the radius of smooth in x and z direction
      x: 10
      z: 10
    sigma: # the sigma of smooth in x and z direction
      x: 20
      z: 1

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 100

  # Optimizer learning rate
  lr: 0.001

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.85

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: ./observed.hdf5

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /home/shaowinw/Desktop/seistorch/examples/models/marmousi_model/true_vp.npy
    vs:
    rho:
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  seabed: /home/shaowinw/Desktop/seistorch/examples/models/marmousi_model/seabed.npy

  wavelet:

  multiple: false

  boundary_saving: true

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /home/shaowinw/Desktop/seistorch/examples/models/marmousi_model/linear_vp.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs:
    rho:
    q:

  # Save the results of FWI
  inv_savePath:

  multiscale:
    - 1.0
    - 3.0
    - 5.0
    - all

  # Time Sampling step
  dt: 0.002

  # Time samples
  nt: 2000

  # Main frequency of ricker wave
  fm: 5.0

  # Spatial grid step size
  h: 20.0

  # Total Shots
  Nshots: 99

  pml:
    N: 50    # PML thickness in number of grid cells