# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: aec

training:

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 100

  # Optimizer learning rate
  lr: 5

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.75

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /public1/home/wangsw/FWI/EFWI/Marmousi/Marmousi2/data/p_shot1.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /home/les_01/wangsw/models/marmousi/elastic_modified/true_vp_z12.5m_x12.5m_expand.npy
    vs: /home/les_01/wangsw/models/marmousi/elastic_modified/true_vs_z12.5m_x12.5m_expand.npy
    rho: /home/les_01/wangsw/models/marmousi/elastic_modified/true_rho_z12.5m_x12.5m_expand.npy
    Q: 

  sources: /home/les_01/wangsw/fwi2d/geometry/marmousi_fixed/sources.pkl

  receivers: /home/les_01/wangsw/fwi2d/geometry/marmousi_fixed/receivers.pkl

  seabed: /home/les_01/wangsw/fwi2d/geometry/marmousi_fixed/sea.npy

  # optional, if you want to use the same random source
  wavelet: 
  #/public1/home/wangsw/FWI/EFWI/Marmousi/Marmousi2/source/true_source.npy

  multiple: false

  boundary_saving: true

  wavelet_delay: 80

  source_type:
    - vz

  receiver_type:
    - p

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /home/les_01/wangsw/models/marmousi/elastic_modified/background_vp_z12.5m_x12.5m_expand.npy
    vs: /home/les_01/wangsw/models/marmousi/elastic_modified/background_vs_z12.5m_x12.5m_expand.npy
    rho: /home/les_01/wangsw/models/marmousi/elastic_modified/background_rho_z12.5m_x12.5m_expand.npy
    Q:

  invlist:
    vp: true
    vs: true
    rho: true
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_10m/Test

  multiscale:
    - 1.0
    - 3.0
    - 5.0
    - 8.0
    - 10.0
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 1000

  # Main frequency of ricker wave
  fm: 15.0

  # Spatial grid step size
  h: 12.5

  # Total Shots
  Nshots: 999

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
