import torch, os, tqdm
torch.cuda.cudnn_enabled = True
torch.backends.cudnn.benchmark = True
from configure import *
torch.random.manual_seed(seed)
import numpy as np
import matplotlib.pyplot as plt
from utils_torch import forward, ricker, generate_pml_coefficients_2d
from torchvision.transforms import Pad


os.makedirs("figures/fwi", exist_ok=True)
os.makedirs("results/fwi", exist_ok=True)

dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")

l2loss = torch.nn.MSELoss()
domain = (nz+2*npml, nx+2*npml)
domain_net = (nz, nx)
# load observed data
obs = np.load("obs.npy")
obs = torch.from_numpy(obs).float().to(dev)

# load wave
wave = ricker(np.arange(nt) * dt-delay*dt, f=fm)

# load true model for comparison
true = np.load("models/true.npy")
# Initial model is generated by Siren
assert os.path.exists("initial_by_siren.npy"), \
    "Please run ifwi.py first to generate initial model by Siren."
init = np.load("initial_by_siren.npy")
init = torch.from_numpy(init).float().to(dev)
init.requires_grad = True

# PML coefficients
pmlc = generate_pml_coefficients_2d(domain, npml)
pmlc = pmlc.to(dev)

# show spectrum of wavelet
plt.figure(figsize=(5, 3))
amp = np.abs(np.fft.fft(wave.cpu().numpy()))
freqs = np.fft.fftfreq(nt, dt)
amp = amp[freqs >= 0]
freqs = freqs[freqs >= 0]
plt.plot(freqs[:50], amp[:50])
plt.xlabel("Frequency (Hz)")
plt.ylabel("Amplitude")

# Geometry
src_x = np.arange(npml, nx+npml, src_x_step)
src_z = np.ones_like(src_x)*srcz

sources = [[src_x, src_z] for src_x, src_z in zip(src_x.tolist(), src_z.tolist())]

# Receivers: [[0, 1, ..., 255], [5, 5, ..., 5], 
#            [0, 1, ..., 255], [5, 5, ..., 5],    
#            [0, 1, ..., 255], [5, 5, ..., 5],
#            ],
receiver_locx = np.arange(npml, nx+npml, 1)
receiver_locz = np.ones_like(receiver_locx)*recz

# The receivers are fixed at the bottom of the model (z=5)
receivers = [[receiver_locx.tolist(), receiver_locz.tolist()]]*len(sources)

opt = torch.optim.Adam([init], lr=0.01)

kwargs = dict(wave=wave, src_list = np.array(sources), domain=domain, dt=dt, h=dh, dev=dev, recz=recz, b=pmlc)
# forward for predicted data
LOSS = []

for epoch in tqdm.trange(EPOCHS):
    # random shots
    src_idx = np.random.choice(len(sources), batch_size, replace=False)
    kwargs.update(src_list = np.array(sources)[src_idx])

    # Denormalize
    vp = init * std_vp + mean_vp
    # forward
    syn = forward(c=vp, **kwargs)
    loss = l2loss(syn, obs[src_idx])
    LOSS.append(loss.item())
    opt.zero_grad()
    loss.backward()
    opt.step()

    if epoch % show_every == 0:
        plt.figure(3, figsize=(6, 8))
        # show inverted
        ax = plt.subplot(311)
        inverted = vp.cpu().detach().numpy().reshape(domain)
        inverted = inverted[npml:-npml, npml:-npml]
        show_kwargs = dict(cmap="seismic", aspect="auto", vmin=true.min(), vmax=true.max())
        ax.imshow(inverted, **show_kwargs)
        # show loss
        ax = plt.subplot(312)
        ax.plot(LOSS)
        plt.yscale("log")
        # show compare
        ax = plt.subplot(313)
        ax.plot(true[:,nx//2], 'r', label="True")
        ax.plot(inverted[:,nx//2], 'b', label="Inverted")
        ax.legend()
        plt.tight_layout()
        # plt.savefig(f"figures/{epoch:04d}.png", dpi=300, bbox_inches="tight")
        plt.savefig(f"figures/fwi/{epoch:04d}.png")
        plt.show()
        np.save(f"results/fwi/inverted{epoch:04d}.npy", inverted)



