# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: elastic

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 1

  # Optimizer learning rate
  lr: 5

  # Milestone decay for lr
  lr_decay: 0.75

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/layer/data/elastic.npy
  #/mnt/data/wangsw/inversion/layer/data/marmousi_elastic_constrho.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/layer/velocity/true_vp.npy
    vs: /mnt/data/wangsw/inversion/layer/velocity/true_vs.npy
    rho: /mnt/data/wangsw/inversion/layer/velocity/rho.npy
    Q: 
    #/mnt/data/wangsw/inversion/layer/data//velocity/q_const.npy

  sources: /home/wangsw/Desktop/wangsw/fwi/geometry/layer/sources.pkl

  receivers: /home/wangsw/Desktop/wangsw/fwi/geometry/layer/receivers.pkl

  wavelet:
  # ./geometry/ricker_lowcut5hz.npy

  source_type:
    - vx

  receiver_type:
    - vx
    - vz

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/layer/velocity/init_vp.npy
    vs: /mnt/data/wangsw/inversion/layer/velocity/init_vs.npy
    rho: /mnt/data/wangsw/inversion/layer/velocity/rho.npy
    Q:

  invlist:
    vp: true
    vs: true
    rho: false
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/layer/Test

  multiscale:
    - 3.0

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 1200

  # Main frequency of ricker wave
  fm: 10.0

  # Spatial grid step size
  h: 10.0

  # Total Shots
  Nshots: 10

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
