# Random seed for pytorch and all shuffle functions
seed: 20230503

name: forward_modeling

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  implicit:
    use: true
    type: sirenscale
    in_features: 2
    out_features: 1
    hidden_features: 1
    hidden_layers: 2
    pretrained:
    vmin: 1000.
    vmax: 5500.

  minibatch: true

  batch_size: 5

  # Number of training epochs
  N_epochs: 10000

  # Optimizer learning rate
  lr: 0.001

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.85

  # decay the lr by each of epochs
  lr_decay: 0.9999

  # Filter order
  filter_ord: 3

geom:

  unit: 1

  # The observer data
  obsPath: ./observed.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: ../../models/marmousi_model_half/true_vp.npy
    vs:
    rho:
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  wavelet:

  multiple: false

  boundary_saving: false

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: ../../models/marmousi_model_half/true_vp.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs:
    rho:
    q:

  # Save the results of FWI
  inv_savePath:

  multiscale:
    - all

  # Time Sampling step
  dt: 0.0019

  # Time samples
  nt: 2100

  # Main frequency of ricker wave
  fm: 8.0

  # Spatial grid step size
  h: 20.0

  # Total Shots
  Nshots: 999

  pml:
    N: 50    # PML thickness in number of grid cells