# Random seed for pytorch and all shuffle functions
seed: 20230503

name: forward_modeling

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 10

  # Number of training epochs
  N_epochs: 50

  # Optimizer learning rate
  lr: 0.001

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.85

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: ./observed_invt_l2.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: ./velocity_model/inverted_l2.npy
    vs:
    rho:
    Q: 
    

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  seabed: ./velocity_model/seabed.npy

  wavelet: ./wavelet/ricker_true.npy

  multiple: false

  boundary_saving: true

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: ./velocity_model/init.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs:
    rho:
    q:

  # Save the results of FWI
  inv_savePath:

  multiscale:
    - 3.0

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 8.0

  # Spatial grid step size
  h: 20.0

  # Total Shots
  Nshots: 999

  pml:
    N: 50    # PML thickness in number of grid cells