# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 150

  # Optimizer learning rate
  lr: 5

  # Milestone decay for lr
  lr_decay: 0.75

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/bp/data/acoustic_bp_part.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/bp/velocity_part/true_vel_z25m_x25m.npy
    vs:
    rho:
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: ./geometry/bp_25m/sources.pkl

  receivers: ./geometry/bp_25m/receivers.pkl

  wavelet:
  # ./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/bp/velocity_part/init_vel_z25m_x25m.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs: false
    rho: false
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_10m/Test

  multiscale:
    - 1.0
    - 3.0
    - 5.0
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 8000

  # Main frequency of ricker wave
  fm: 5.0

  # Spatial grid step size
  h: 25.0

  # Total Shots
  Nshots: 100

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor