# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: elastic

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 50

  # Optimizer learning rate
  lr: 5

  # Milestone decay for lr
  lr_decay: 0.85

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/overthrust_15m/data/overthrust_15m_elastic.npy
  #/mnt/data/wangsw/inversion/marmousi_10m/data/marmousi_elastic_constrho.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/overthrust_15m/velocity/true_vp.npy
    vs: /mnt/data/wangsw/inversion/overthrust_15m/velocity/true_vs.npy
    rho: /mnt/data/wangsw/inversion/overthrust_15m/velocity/rho.npy
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: ./geometry/overthrust_15m/sources.pkl

  receivers: ./geometry/overthrust_15m/receivers.pkl

  wavelet:
  # ./geometry/ricker_lowcut5hz.npy

  source_type:
    - vz

  receiver_type:
    - vx
    - vz

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/overthrust_15m/velocity/init_vp.npy
    vs: /mnt/data/wangsw/inversion/overthrust_15m/velocity/init_vs.npy
    rho: /mnt/data/wangsw/inversion/overthrust_15m/velocity/rho.npy
    Q:

  invlist:
    vp: true
    vs: true
    rho: false
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_10m/Test

  multiscale:
    - 3.0
    - 5.0
    - 8.0
    - 10.0
    - all

  # Time Sampling step
  dt: 0.002

  # Time samples
  nt: 2000

  # Main frequency of ricker wave
  fm: 10.0

  # Spatial grid step size
  h: 15.0

  # Total Shots
  Nshots: 100

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor