# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

# Using autodiff or not
autodiff: true

equation: elastic

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 50

  # Optimizer learning rate
  lr: 5

  lr_decay: 0.95

  # when >2, can save gpu memory
  save_interval: 10

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/marmousi_20m/data/marmousi_elastic_obn.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/marmousi_20m/velocity/true_vp.npy
    vs: /mnt/data/wangsw/inversion/marmousi_20m/velocity/true_vs.npy
    rho: /mnt/data/wangsw/inversion/marmousi_20m/velocity/rho.npy
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_20m/data//velocity/q_const.npy

  sources: ./geometry/marmousi_obn/sources.pkl

  receivers: ./geometry/marmousi_obn/receivers.pkl

  source_type:
    - vz

  receiver_type:
    - vx
    - vz
  
  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/marmousi_20m/velocity/linear_vp.npy
    vs: /mnt/data/wangsw/inversion/marmousi_20m/velocity/linear_vs.npy
    rho: /mnt/data/wangsw/inversion/marmousi_20m/velocity/rho.npy
    Q:

  invlist:
    vp: true
    vs: true
    rho: true
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_20m/Test

  multiscale: 
    - 3.0
    - 5.0

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 5.

  # Spatial grid step size
  h: 20.0

  # Total receivers
  Nreceivers: 561

  # Total Shots
  Nshots: 111

  # Probe init_x coordinate in grid cells
  ipx: 1

  # Source init_x coordinate in grid cells
  isx: 1

  # Probe x-coordinates in grid cells
  px:
  
  # Probe y-coordinates in grid cells
  py: 24

  # Spacing, in number grid cells, between probe points
  pd: 1

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
