# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

# Using autodiff or not
autodiff: true

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 80

  # Optimizer learning rate
  lr: 10

  lr_decay: 0.5

  # when >2, can save gpu memory
  save_interval: 2

  # Normalize the obs and syn for backward
  normalize: false

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/marmousi_20m/data/marmousi_elastic.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/marmousi_20m/velocity/true_vp.npy
    vs: /mnt/data/wangsw/inversion/marmousi_20m/velocity/true_vs.npy
    rho: /mnt/data/wangsw/inversion/marmousi_20m/velocity/rho.npy
    #/mnt/data/wangsw/inversion/marmousi_20m//velocity/rho_const.npy
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_20m//velocity/q_const.npy

  source_type:
    - vz

  receiver_type:
    - vx
    - vz
  
  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/marmousi_20m/velocity/init_vp.npy
    vs: /mnt/data/wangsw/inversion/marmousi_20m/velocity/init_vs.npy
    rho: /mnt/data/wangsw/inversion/marmousi_20m/velocity/rho.npy
    Q:

  invlist:
    vp: true
    vs: true
    rho: false
    q: false

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_20m/results/test_autodiff

  multiscale: 
    - 3.0

  use_design_region: true

  # Initialization of the design region, either 'rand', 'half', or 'blank'
  init: blank

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 5.

  # Spatial grid step size
  h: 20.0

  # Total receivers
  Nreceivers: 561

  # Total Shots
  Nshots: 111

  # Probe init_x coordinate in grid cells
  ipx: 1

  # Source init_x coordinate in grid cells
  isx: 1

  # Probe x-coordinates in grid cells
  px:
    
  # Probe y-coordinates in grid cells
  py: 1

  # Spacing, in number grid cells, between probe points
  pd: 1

  # Source x-coordinate in grid cells
  src_x: 1

  # Source y-coordinate in grid cells
  src_y: 1

  # Spacing, in number grid cells, between source points
  src_d: 5

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
