# Random seed for pytorch and all shuffle functions
seed: 10

name: fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

training:

  sample_shot: false

  shot_per_epoch: 10

  # Number of training epochs
  N_epochs: 40

  # Optimizer learning rate
  lr: 10

  lr_decay: 0.5

  # Limit the maximum number of samples to this number 
  # If unspecified then all samples available for the specified vowel classes and gender are used
  max_samples: 12


  # when >2, can save gpu memory
  save_interval: 10

  # Normalize the obs and syn for backward
  normalize: false

  # Filter order
  filter_ord: 1

geom:

  # The observer data
  obsPath: /public1/home/wangsw/FWI/AFWI/data/marmousi_MERGECODE.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/true_vp.npy
    vs: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/true_vs.npy
    rho: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/rho.npy
    Q:

  source_type:
    - vz

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/init_vp.npy
    vs: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/init_vs.npy
    rho: /public1/home/wangsw/FWI/EFWI/Marmousi/marmousi_10m/velocity/rho.npy
    Q:

  # Save the results of FWI
  inv_savePath: /public1/home/wangsw/FWI/AFWI/Hessian_free2

  multiscale: 
    - 3.0
    - 5.0
    - 8.0
    - 10.0
    - 15.0
    - 18.0
    - 20.0

  use_design_region: true

  # Initialization of the design region, either 'rand', 'half', or 'blank'
  init: blank


  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 15.

  # Spatial grid step size
  h: 10.0

  # Total receivers
  Nreceivers: 1122

  # Total Shots
  Nshots: 111

  # Probe init_x coordinate in grid cells
  ipx: 1

  # Source init_x coordinate in grid cells
  isx: 1

  # Probe x-coordinates in grid cells
  px:
    
  # Probe y-coordinates in grid cells
  py: 1

  # Spacing, in number grid cells, between probe points
  pd: 1

  # Source x-coordinate in grid cells
  src_x: 1

  # Source y-coordinate in grid cells
  src_y: 1

  # Spacing, in number grid cells, between source points
  src_d: 10

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
