# Random seed for pytorch and all shuffle functions
seed: 20230503

name: coding_fwi

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic

training:

  minibatch: true

  batch_size: 20

  # Number of training epochs
  N_epochs: 100

  # Optimizer learning rate
  lr: 5

  # decay the lr by each of epochs
  lr_decay: 0.995

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.75

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: /mnt/data/wangsw/inversion/elastic_marmousi/data/acoustic_fixed.npy

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: /mnt/data/wangsw/inversion/elastic_marmousi/velocity/true_vp_z12.5m_x12.5m_expand.npy
    vs:
    rho:
    Q: 

  sources: ./geometry/marmousi_fixed/sources.pkl

  receivers: ./geometry/marmousi_fixed/receivers.pkl

  # optional, if you want to use the same random source
  wavelet:

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: /mnt/data/wangsw/inversion/elastic_marmousi/velocity/linear_vp_z12.5m_x12.5m_expand.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs: false
    rho: false
    q: false

  # using checkpoint for saving memory
  ckpt: true

  # Save the results of FWI
  inv_savePath: /mnt/data/wangsw/inversion/marmousi_10m/Test

  multiscale:
    - 1.0
    - 3.0
    - 5.0
    - 8.0
    - 10.0
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 4000

  # Main frequency of ricker wave
  fm: 10.0

  # Spatial grid step size
  h: 12.5

  # Total Shots
  Nshots: 999

  pml:
    N: 50    # PML thickness in number of grid cells
    p: 4   # PML polynomial order
    max: 20.0 # PML max dampening factor
