# Random seed for pytorch and all shuffle functions
seed: 20230503

name: FWI_AD

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic_habc

training:

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 10

  # Number of training epochs
  N_epochs: 1

  # Optimizer learning rate
  lr:

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.85

  # decay the lr by each of epochs
  lr_decay: 0.95

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: ./shot_gather.hdf5

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: ./velocity_model/true.npy
    vs:
    rho:
    Q: 
    #/mnt/data/wangsw/inversion/marmousi_10m/data//velocity/q_const.npy

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  wavelet:

  multiple: false

  boundary_saving: false

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - h1

  receiver_type:
    - h1

  # Inital Wave speed model from disk_file
  initPath: 
    vp: ./velocity_model/init.npy
    vs:
    rho:
    Q:

  invlist:
    vp: true
    vs:
    rho:
    q:

  # Save the results of FWI
  inv_savePath:

  multiscale:
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 1500

  # Main frequency of ricker wave
  fm: 5.0

  # Spatial grid step size
  h: 10.0

  # Total Shots
  Nshots: 999

  boundary:
    type: habc
    width: 50