# Random seed for pytorch and all shuffle functions
seed: 20230503

name: forward_modeling

# Data type to use for tensors, either float32 or float64
dtype: float32

equation: acoustic_vti_lsrtm_pml

backend: jax

training:

  implicit:
    use: false
    pretrained:

  minibatch: true

  batch_size: 10

  # Number of training epochs
  N_epochs: 30

  # Optimizer learning rate
  lr: 0.001

  # Decay the learning rate by each of multi-scale
  scale_decay: 0.99

  # decay the lr by each of epochs
  lr_decay: 0.95

  # Filter order
  filter_ord: 3

geom:

  # The observer data
  obsPath: ./shot_gather_tti_born.hdf5

  # Wave speed model from disk_file for forward modeling
  truePath:
    vp: ./models/vp.npy
    epsilon: ./models/epsilon.npy
    delta: ./models/delta.npy
    m:

  sources: ./geometry/sources.pkl

  receivers: ./geometry/receivers.pkl

  seabed:

  wavelet:

  multiple: false

  boundary_saving: false

  wavelet_delay: 256

  wavelet_inverse: false
  #./geometry/ricker_lowcut5hz.npy

  source_type:
    - p1

  receiver_type:
    - sp1

  seabed: ./models/seabed.npy

  # Inital Wave speed model from disk_file
  initPath: 
    vp: ./models/vp_smooth.npy
    epsilon: ./models/epsilon.npy
    delta: ./models/delta.npy
    m: ./models/zero.npy

  invlist:
    vp: false
    epsilon: false
    delta: false
    m: true

  # Save the results of FWI
  inv_savePath:

  multiscale:
    - all

  # Time Sampling step
  dt: 0.001

  # Time samples
  nt: 2001

  # Main frequency of ricker wave
  fm: 18.0

  # Spatial grid step size
  h: 10.0

  # Total Shots
  Nshots: 999

  boundary:
    type: pml
    width: 50